stages:
  preprocessing:
    cmd: python src/preprocess.py --config=params.yaml
    deps:
      - data/raw/depth_X/train
      - data/raw/depth_y/train
      - src/preprocess.py
    params:
      - data.img_size
      - data.baseline
      - data.focal_length
      - data.max_depth
    outs:
      - data/processed/depth_X/train:
          persist: true
      - data/processed/depth_y/train:
          persist: true

  training:
    cmd: python -u src/training.py --config=params.yaml
    deps:
      - data/processed/depth_X/train
      - data/processed/depth_y/train
      - data/processed/depth_X/val
      - data/processed/depth_y/val
      - src/training.py
      - src/model.py
      - src/data_loader.py
      - src/metrics.py
    params:
      - data
      - model
      - training
      - augmentation
      - mlflow
    outs:
      - saved_models/model.pth

  evaluate:
    cmd: python src/evaluate.py --config=params.yaml
    deps:
      - saved_models/model.pth
      - data/processed/depth_X/test
      - data/processed/depth_y/test
      - src/evaluate.py
      - src/metrics.py
    params:
      - data
      - model
      - mlflow
    metrics:
      - metrics.json:
          cache: false

  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
      - src/log_production_model.py
      - saved_models/model.pth
      - metrics.json
    params:
      - mlflow
    outs:
      - saved_models/production_model.pth

  export_onnx:
    cmd: python src/export_onnx.py --config=params.yaml
    deps:
      - saved_models/production_model.pth
      - src/export_onnx.py
      - src/model.py
    params:
      - export
      - model
    outs:
      - saved_models/model.onnx

  push_to_hf:
    cmd: python src/push_to_hf.py --config=params.yaml
    deps:
      - saved_models/model.onnx
      - src/push_to_hf.py
    params:
      - export.hf_repo_id
